name: Compile Protocol Buffers
on:
  push:
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
      - 'questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*'
      - 'questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/*'
  pull_request_target:
    branches:
      - main
    paths:
      - 'protos/*'
      - 'questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*'
      - 'unity/Assets/QuestNav/Protos/Generated/*'
  workflow_dispatch:
jobs:
  compile-protobufs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download QuickBuf plugin
        id: download-quickbuf
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://repo1.maven.org'
          repository: 'maven2'
          groupId: 'us.hebi.quickbuf'
          artifactId: 'protoc-gen-quickbuf'
          version: '1.4'
          extension: 'exe'
          classifier: 'linux-x86_64'

      - name: Setup QuickBuf
        run: chmod +x ${{ steps.download-quickbuf.outputs.file }}

      - name: Download NanoPB
        id: download-nanopb
        run: wget -O nanopb.tar.gz https://jpa.kapsi.fi/nanopb/download/nanopb-0.4.9.1-linux-x86.tar.gz

      - name: Extract NanoPB
        run: tar -xzf nanopb.tar.gz

      - name: Setup NanoPB
        run: chmod +x nanopb-0.4.9.1-linux-x86/generator-bin/nanopb_generator

      - name: Generate C# protobuf
        run: protoc -I="protos" --csharp_out=unity/Assets/QuestNav/Protos/Generated protos/*.proto

      - name: Generate C++ protobufs
        run: |
          # Set variables
          NANOPB_GENERATOR="./nanopb-0.4.9.1-linux-x86/generator-bin/nanopb_generator"
            OUTPUT_DIR="questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/"
            PROTO_DIR="protos/"

            # Create output directory if it doesn't exist
            mkdir -p "$OUTPUT_DIR"

            # Find all .proto files and generate NanoPB code for each
            for proto_file in "$PROTO_DIR"*.proto; do
                if [ -f "$proto_file" ]; then
                    echo "Generating NanoPB code for: $proto_file"
                    "$NANOPB_GENERATOR" --cpp-descriptors --output-dir="$OUTPUT_DIR" -I="$PROTO_DIR" "$proto_file"

                    # Check if the generation was successful
                    if [ $? -eq 0 ]; then
                        echo "✓ Successfully generated: $proto_file"
                    else
                        echo "✗ Failed to generate: $proto_file"
                        exit 1
                    fi
                fi
            done

            echo "NanoPB generation complete!"

      - name: Move C++ header files
        run: mv questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*.pb.h questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/

      - name: Generate Java QuickBuffers
        run: |
          protoc \
            -I="protos" \
            --plugin=protoc-gen-quickbuf=${{ steps.download-quickbuf.outputs.file }} \
            --quickbuf_out=gen_descriptors=true,indent=4:questnav-lib/src/main/java/ \
            protos/*.proto

      - name: Commit all generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: Generated Protocol Buffers'
          file_pattern: 'unity/Assets/QuestNav/Protos/Generated/*.cs
            questnav-lib/src/main/native/include/gg/questnav/questnav/protos/generated/*.pb.h
            questnav-lib/src/main/native/cpp/gg/questnav/questnav/protos/generated/*.pb.c
            questnav-lib/src/main/java/gg/questnav/questnav/protos/generated/*.java'